[project]
name = "film-analysys"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "numpy>=2.2.3",
    "polars>=1.23.0",
    "streamlit>=1.42.2",
]
